#################################################
# Base configuration
#################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: Release
  DEFAULT_WINDOWS_CMAKE_OPTIONS: -DENABLE_NON_FREE_CODECS=YES -DENABLE_OPENH264=YES -DENABLE_UPDATE_CHECK=YES


#################################################
# Visual Studio 2017
#################################################

.job-windows-vs2017:

  before_script:
    - 'call %VS14COMMONTOOLS%\vsvars32.bat'
    - python prepare.py %DEFAULT_WINDOWS_CMAKE_OPTIONS% %CMAKE_OPTIONS%

  stage: build

  tags: [ "windows" ]

  script:
    - 'msbuild.exe /p:MDILCompile=true /p:Platform=%PROJECT_ARCHITECTURE% /t:build /p:Configuration=%BUILD_TYPE% "%SOLUTION%"'

job-windows-vs2017-ARM:
  variables:
    PROJECT_ARCHITECTURE: ARM
    SOLUTION: WORK\win10-ARM\cmake\Project.sln

  extends: .job-windows-vs2017

job-windows-vs2017-X86:
  variables:
    PROJECT_ARCHITECTURE: x64
    SOLUTION: WORK\win10-x86\cmake\Project.sln

  extends: .job-windows-vs2017

job-windows-vs2017-X64:
  variables:
    PROJECT_ARCHITECTURE: Win32
    SOLUTION: WORK\win10-x64\cmake\Project.sln

  extends: .job-windows-vs2017

#  artifacts:
#    paths:
#      - WORK/desktop/Build/linphone_package/%PACKAGE_NAME%-*-win32.exe
#    expire_in: 1 week

#################################################
# Deploy
#################################################

#job-windows-deploy:
#
#  stage: deploy
#  tags: [ "deploy" ]
#
#  dependencies:
#    - job-windows-vs2015
#
#  script:
#    - scp WORK/desktop/Build/linphone_package/$PACKAGE_NAME-*-win32.exe $DEPLOY_SERVER:$WINDOWS_UPLOAD_DIRECTORY/

stages:
  - build
#  - package
#  - deploy