//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSN.Resa.Vns.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSN.Resa.Vns.Locale.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access levels.
        /// </summary>
        public static string AccessLevels {
            get {
                return ResourceManager.GetString("AccessLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Strategy.
        /// </summary>
        public static string AcquisitionStrategyType {
            get {
                return ResourceManager.GetString("AcquisitionStrategyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active callee phone number.
        /// </summary>
        public static string ActiveCalleePhoneNumber {
            get {
                return ResourceManager.GetString("ActiveCalleePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available balance.
        /// </summary>
        public static string AvailableBalance {
            get {
                return ResourceManager.GetString("AvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AXB management system.
        /// </summary>
        public static string AXBManagementSystem {
            get {
                return ResourceManager.GetString("AXBManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance successfully charged.
        /// </summary>
        public static string BalanceSuccessfullyCharged {
            get {
                return ResourceManager.GetString("BalanceSuccessfullyCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be right back.
        /// </summary>
        public static string BeRightBack {
            get {
                return ResourceManager.GetString("BeRightBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing cycle.
        /// </summary>
        public static string BillingCycle {
            get {
                return ResourceManager.GetString("BillingCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking list.
        /// </summary>
        public static string BookingList {
            get {
                return ResourceManager.GetString("BookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        public static string Callback {
            get {
                return ResourceManager.GetString("Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking.
        /// </summary>
        public static string CallBooking {
            get {
                return ResourceManager.GetString("CallBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking default setting.
        /// </summary>
        public static string CallBookingDefaultSetting {
            get {
                return ResourceManager.GetString("CallBookingDefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking default settings successfully updated.
        /// </summary>
        public static string CallBookingDefaultSettingsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("CallBookingDefaultSettingsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking id.
        /// </summary>
        public static string CallBookingId {
            get {
                return ResourceManager.GetString("CallBookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking list.
        /// </summary>
        public static string CallBookingList {
            get {
                return ResourceManager.GetString("CallBookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call booking type.
        /// </summary>
        public static string CallBookingType {
            get {
                return ResourceManager.GetString("CallBookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call direction.
        /// </summary>
        public static string CallDirection {
            get {
                return ResourceManager.GetString("CallDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callee phone number.
        /// </summary>
        public static string CalleePhoneNumber {
            get {
                return ResourceManager.GetString("CalleePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callee phone numbers.
        /// </summary>
        public static string CalleePhoneNumbers {
            get {
                return ResourceManager.GetString("CalleePhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callee virtual number.
        /// </summary>
        public static string CalleeVirtualNumber {
            get {
                return ResourceManager.GetString("CalleeVirtualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller phone number.
        /// </summary>
        public static string CallerPhoneNumber {
            get {
                return ResourceManager.GetString("CallerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallerSubscriberIdentificationCard.
        /// </summary>
        public static string CallerSubscriberIdentificationCard {
            get {
                return ResourceManager.GetString("CallerSubscriberIdentificationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller virtual number.
        /// </summary>
        public static string CallerVirtualNumber {
            get {
                return ResourceManager.GetString("CallerVirtualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call termination reason.
        /// </summary>
        public static string CallTerminationReason {
            get {
                return ResourceManager.GetString("CallTerminationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chained call booking.
        /// </summary>
        public static string ChainedCallBooking {
            get {
                return ResourceManager.GetString("ChainedCallBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Model.
        /// </summary>
        public static string CompensationModel {
            get {
                return ResourceManager.GetString("CompensationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption unit.
        /// </summary>
        public static string ConsumptionUnit {
            get {
                return ResourceManager.GetString("ConsumptionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer successfully disabled.
        /// </summary>
        public static string CustomerSuccessfullyDisabled {
            get {
                return ResourceManager.GetString("CustomerSuccessfullyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer successfully enabled.
        /// </summary>
        public static string CustomerSuccessfullyEnabled {
            get {
                return ResourceManager.GetString("CustomerSuccessfullyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier.
        /// </summary>
        public static string Dossier {
            get {
                return ResourceManager.GetString("Dossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDuration.
        /// </summary>
        public static string EffectiveDuration {
            get {
                return ResourceManager.GetString("EffectiveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extortion.
        /// </summary>
        public static string Extortion {
            get {
                return ResourceManager.GetString("Extortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishedAt.
        /// </summary>
        public static string FinishedAt {
            get {
                return ResourceManager.GetString("FinishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoarding.
        /// </summary>
        public static string Hoarding {
            get {
                return ResourceManager.GetString("Hoarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input invalid.
        /// </summary>
        public static string InputInvalid {
            get {
                return ResourceManager.GetString("InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Required.
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is customer assignable.
        /// </summary>
        public static string IsCustomerAssignable {
            get {
                return ResourceManager.GetString("IsCustomerAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuedAt.
        /// </summary>
        public static string IssuedAt {
            get {
                return ResourceManager.GetString("IssuedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of hygiene.
        /// </summary>
        public static string LackOfHygiene {
            get {
                return ResourceManager.GetString("LackOfHygiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime.
        /// </summary>
        public static string Lifetime {
            get {
                return ResourceManager.GetString("Lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum cumulative duration of calls.
        /// </summary>
        public static string MaximumCumulativeDurationOfCalls {
            get {
                return ResourceManager.GetString("MaximumCumulativeDurationOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of calls.
        /// </summary>
        public static string MaximumNumberOfCalls {
            get {
                return ResourceManager.GetString("MaximumNumberOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string Missed {
            get {
                return ResourceManager.GetString("Missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recently used.
        /// </summary>
        public static string MostRecentlyUsed {
            get {
                return ResourceManager.GetString("MostRecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi occupancy.
        /// </summary>
        public static string MultiOccupancy {
            get {
                return ResourceManager.GetString("MultiOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Identification Number.
        /// </summary>
        public static string NationalIdentificationNumber {
            get {
                return ResourceManager.GetString("NationalIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer successfully added.
        /// </summary>
        public static string NewCustomerSuccessfullyAdded {
            get {
                return ResourceManager.GetString("NewCustomerSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pool successfully added.
        /// </summary>
        public static string NewPoolSuccessfullyAdded {
            get {
                return ResourceManager.GetString("NewPoolSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pricing policy successfully added.
        /// </summary>
        public static string NewPricingPolicySuccessfullyAdded {
            get {
                return ResourceManager.GetString("NewPricingPolicySuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextPage.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to display.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Operational.
        /// </summary>
        public static string NonOperational {
            get {
                return ResourceManager.GetString("NonOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no record in the selected interval .
        /// </summary>
        public static string NoRecordInTheSelectedInterval {
            get {
                return ResourceManager.GetString("NoRecordInTheSelectedInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid after.
        /// </summary>
        public static string NotValidAfter {
            get {
                return ResourceManager.GetString("NotValidAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid before.
        /// </summary>
        public static string NotValidBefore {
            get {
                return ResourceManager.GetString("NotValidBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ongoing calls.
        /// </summary>
        public static string NumberOfOngoingCalls {
            get {
                return ResourceManager.GetString("NumberOfOngoingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of operational bookings.
        /// </summary>
        public static string NumberOfOperationalBookings {
            get {
                return ResourceManager.GetString("NumberOfOperationalBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows.
        /// </summary>
        public static string NumberOfRows {
            get {
                return ResourceManager.GetString("NumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sim cards.
        /// </summary>
        public static string NumberOfSimCards {
            get {
                return ResourceManager.GetString("NumberOfSimCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of successful calls.
        /// </summary>
        public static string NumberOfSuccessfulCalls {
            get {
                return ResourceManager.GetString("NumberOfSuccessfulCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of total calls.
        /// </summary>
        public static string NumberOfTotalCalls {
            get {
                return ResourceManager.GetString("NumberOfTotalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of total text messages.
        /// </summary>
        public static string NumberOfTotalTextMessages {
            get {
                return ResourceManager.GetString("NumberOfTotalTextMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeral.
        /// </summary>
        public static string Numeral {
            get {
                return ResourceManager.GetString("Numeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objection.
        /// </summary>
        public static string Objection {
            get {
                return ResourceManager.GetString("Objection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the phone.
        /// </summary>
        public static string OnThePhone {
            get {
                return ResourceManager.GetString("OnThePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational.
        /// </summary>
        public static string Operational {
            get {
                return ResourceManager.GetString("Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out to lunch.
        /// </summary>
        public static string OutToLunch {
            get {
                return ResourceManager.GetString("OutToLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable amount.
        /// </summary>
        public static string PayableAmount {
            get {
                return ResourceManager.GetString("PayableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay per minute.
        /// </summary>
        public static string PayPerMinute {
            get {
                return ResourceManager.GetString("PayPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay per session.
        /// </summary>
        public static string PayPerSession {
            get {
                return ResourceManager.GetString("PayPerSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy model.
        /// </summary>
        public static string PolicyModel {
            get {
                return ResourceManager.GetString("PolicyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool display name.
        /// </summary>
        public static string PoolDisplayName {
            get {
                return ResourceManager.GetString("PoolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool successfully updated.
        /// </summary>
        public static string PoolSeccessfullyUpdated {
            get {
                return ResourceManager.GetString("PoolSeccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool successfully attached to customer.
        /// </summary>
        public static string PoolSuccessfullyAttachedToCustomer {
            get {
                return ResourceManager.GetString("PoolSuccessfullyAttachedToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pool successfully detached from customer.
        /// </summary>
        public static string PoolSuccessfullyDetachedFromCustomer {
            get {
                return ResourceManager.GetString("PoolSuccessfullyDetachedFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousPage.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Policy.
        /// </summary>
        public static string PricingPolicy {
            get {
                return ResourceManager.GetString("PricingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing policy id.
        /// </summary>
        public static string PricingPolicyId {
            get {
                return ResourceManager.GetString("PricingPolicyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person email.
        /// </summary>
        public static string PrimaryContactPersonEmail {
            get {
                return ResourceManager.GetString("PrimaryContactPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person name.
        /// </summary>
        public static string PrimaryContactPersonName {
            get {
                return ResourceManager.GetString("PrimaryContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person phone number.
        /// </summary>
        public static string PrimaryContactPersonPhoneNumber {
            get {
                return ResourceManager.GetString("PrimaryContactPersonPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomized.
        /// </summary>
        public static string Randomized {
            get {
                return ResourceManager.GetString("Randomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received at.
        /// </summary>
        public static string ReceivedAt {
            get {
                return ResourceManager.GetString("ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver phone number.
        /// </summary>
        public static string ReceiverPhoneNumber {
            get {
                return ResourceManager.GetString("ReceiverPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiverSubscriberIdentificationCard.
        /// </summary>
        public static string ReceiverSubscriberIdentificationCard {
            get {
                return ResourceManager.GetString("ReceiverSubscriberIdentificationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver virtual number.
        /// </summary>
        public static string ReceiverVirtualNumber {
            get {
                return ResourceManager.GetString("ReceiverVirtualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving informations.
        /// </summary>
        public static string ReceivingInformation {
            get {
                return ResourceManager.GetString("ReceivingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record payment information.
        /// </summary>
        public static string RecordPaymentInformation {
            get {
                return ResourceManager.GetString("RecordPaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining cumulative duration of calls.
        /// </summary>
        public static string RemainingCumulativeDurationOfCalls {
            get {
                return ResourceManager.GetString("RemainingCumulativeDurationOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining number of calls.
        /// </summary>
        public static string RemainingNumberOfCalls {
            get {
                return ResourceManager.GetString("RemainingNumberOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing.
        /// </summary>
        public static string Ringing {
            get {
                return ResourceManager.GetString("Ringing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotary call booking.
        /// </summary>
        public static string RotaryCallBooking {
            get {
                return ResourceManager.GetString("RotaryCallBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        public static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender phone number.
        /// </summary>
        public static string SenderPhoneNumber {
            get {
                return ResourceManager.GetString("SenderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender virtual number.
        /// </summary>
        public static string SenderVirtualNumber {
            get {
                return ResourceManager.GetString("SenderVirtualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service consumption unit.
        /// </summary>
        public static string ServiceConsumptionUnit {
            get {
                return ResourceManager.GetString("ServiceConsumptionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim card pool.
        /// </summary>
        public static string SimCardPool {
            get {
                return ResourceManager.GetString("SimCardPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim card pool name.
        /// </summary>
        public static string SimCardPoolName {
            get {
                return ResourceManager.GetString("SimCardPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim cards.
        /// </summary>
        public static string SimCards {
            get {
                return ResourceManager.GetString("SimCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim card successfully deleted.
        /// </summary>
        public static string SimcardSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SimcardSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple call booking.
        /// </summary>
        public static string SimpleCallBooking {
            get {
                return ResourceManager.GetString("SimpleCallBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single occupancy.
        /// </summary>
        public static string SingleOccupancy {
            get {
                return ResourceManager.GetString("SingleOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted.
        /// </summary>
        public static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartedAt.
        /// </summary>
        public static string StartedAt {
            get {
                return ResourceManager.GetString("StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Details.
        /// </summary>
        public static string StepDetails {
            get {
                return ResourceManager.GetString("StepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepwise.
        /// </summary>
        public static string Stepwise {
            get {
                return ResourceManager.GetString("Stepwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Identification Card pool type.
        /// </summary>
        public static string SubscriberIdentificationCardPoolType {
            get {
                return ResourceManager.GetString("SubscriberIdentificationCardPoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax identification number.
        /// </summary>
        public static string TaxIdentificationNumber {
            get {
                return ResourceManager.GetString("TaxIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal.
        /// </summary>
        public static string Temporal {
            get {
                return ResourceManager.GetString("Temporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket FollowUp.
        /// </summary>
        public static string TicketFollowUp {
            get {
                return ResourceManager.GetString("TicketFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times after.
        /// </summary>
        public static string TimesAfter {
            get {
                return ResourceManager.GetString("TimesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times before.
        /// </summary>
        public static string TimesBefore {
            get {
                return ResourceManager.GetString("TimesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toman.
        /// </summary>
        public static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking number.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction list.
        /// </summary>
        public static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the requested resource.
        /// </summary>
        public static string UnableToAccessTheRequestedResource {
            get {
                return ResourceManager.GetString("UnableToAccessTheRequestedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassignable to customer.
        /// </summary>
        public static string UnassignableToCustomer {
            get {
                return ResourceManager.GetString("UnassignableToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underselling.
        /// </summary>
        public static string Underselling {
            get {
                return ResourceManager.GetString("Underselling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuspend.
        /// </summary>
        public static string Unsuspend {
            get {
                return ResourceManager.GetString("Unsuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuspended.
        /// </summary>
        public static string Unsuspended {
            get {
                return ResourceManager.GetString("Unsuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed successfully.
        /// </summary>
        public static string UpdateCompletedSuccessfully {
            get {
                return ResourceManager.GetString("UpdateCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activities list.
        /// </summary>
        public static string UserActivitiesList {
            get {
                return ResourceManager.GetString("UserActivitiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted.
        /// </summary>
        public static string UserSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UserSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully disabled.
        /// </summary>
        public static string UserSuccessfullyDisabled {
            get {
                return ResourceManager.GetString("UserSuccessfullyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully enabled.
        /// </summary>
        public static string UserSuccessfullyEnabled {
            get {
                return ResourceManager.GetString("UserSuccessfullyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet information.
        /// </summary>
        public static string WalletInformation {
            get {
                return ResourceManager.GetString("WalletInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelist.
        /// </summary>
        public static string Whitelist {
            get {
                return ResourceManager.GetString("Whitelist", resourceCulture);
            }
        }
    }
}
